### ISSUE TITLE
获得视频中物体的摆动频率

### ISSUE THREAD

**Issue by liuqunzhong** [luoye2333/ResNetLSTM#2]
请问CSDN中你提到的“获得视频中物体的摆动频率”实验，最后测试效果怎么样呢？

**Comment by luoye2333** [comment]
误差1Hz之内吧，不过只是用人工生成的数据。后面我就没继续做了。
感兴趣的话可以用文章里的代码验证，或者直接用下面的代码
import ResNetLSTM as rnl
n=rnl.net()
n.load('2019-08-14-18-38-43.pth')#载入训练好的模型
#测试
n.eval('Q:\workplace\code\python\ResNetLSTM\sample\\2019-8-15-15-38-12')





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luoye2333/ResNetLSTM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 晚上6:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[luoye2333/ResNetLSTM] 获得视频中物体的摆动频率 (Issue #2)





 
请问CSDN中你提到的“获得视频中物体的摆动频率”实验，最后测试效果怎么样呢？

**Comment by liuqunzhong** [comment]
谢谢
